During a network partition between DC and Cloud, the following scenario led the discovery client to get "null" applications. If the outage happened exactly at the time of unmarshalling discovery data, a "null" value is returned by the discovery unmarshaller. If the network connection failed at the time of connection or when the response is read - it wouldn't be a problem. That is why this problem was not affecting all the servers. Below is the sample exception trace that indicates the problem
2012-11-09 00:24:59,826 WARN com.netflix.discovery.provider.DiscoveryJerseyProvider:1 [DiscoveryClient_CacheRefresher] [log] Cannot read the object for :class com.netflix.discovery.shared.Applications
com.thoughtworks.xstream.io.StreamException: : java.net.SocketTimeoutException: Read timed out
at com.thoughtworks.xstream.io.json.JettisonMappedXmlDriver.createReader(JettisonMappedXmlDriver.java:95)
at com.thoughtworks.xstream.XStream.fromXML(XStream.java:921)
at com.netflix.discovery.converters.EntityBodyConverter.read(EntityBodyConverter.java:60)
at com.netflix.discovery.provider.DiscoveryJerseyProvider.readFrom(DiscoveryJerseyProvider.java:92)
at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:553)
at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:506)
at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:567)
at com.netflix.discovery.DiscoveryClient.access$1200(DiscoveryClient.java:87)
at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1311)
at java.util.TimerThread.mainLoop(Timer.java:534)
at java.util.TimerThread.run(Timer.java:484)
Caused by: javax.xml.stream.XMLStreamException: java.net.SocketTimeoutException: Read timed out
at org.codehaus.jettison.AbstractXMLInputFactory.createXMLStreamReader(AbstractXMLInputFactory.java:108)
at org.codehaus.jettison.AbstractXMLInputFactory.createXMLStreamReader(AbstractXMLInputFactory.java:93)
at com.thoughtworks.xstream.io.json.JettisonMappedXmlDriver.createReader(JettisonMappedXmlDriver.java:93)
... 10 more
Caused by: java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:146)
at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:187)
at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:138)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
at java.io.Buffe