Move back to java7 compatibility.
Spring Cloud Netflix is still java7 compatible.

When using java7 to build, the following error occurs because servo is java8 only.

java.lang.UnsupportedClassVersionError: com/netflix/servo/monitor/Monitors
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:126)
	at com.netflix.discovery.BackUpRegistryTest.setUp(BackUpRegistryTest.java:71)

Spring Cloud Netflix still uses the java7 servo.

Building with java8 and targeting java7 still works and maintains the required compatibility.